# Generated by Django 4.0.6 on 2022-07-12 02:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='height',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='width',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='banner_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[600, 600], upload_to='album_banners'),
        ),
    ]
