# Generated by Django 4.0.6 on 2022-07-12 02:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_height_album_width_alter_album_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[2048, 2048], upload_to='photos'),
        ),
    ]
